
version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server/
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./server/build:/app/build
  client:
    build:
      dockerfile: Dockerfile
      context: ./client/
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - ./client:/app